language: r
cache: packages
addons:
  apt:
    packages:
      - libxml2-dev
r_packages:
  - devtools
  - resourcer
r_github_packages:
  - datashield/DSI@master
  - obiba/opalr@master
warnings_are_errors: true