language: r
cache: packages
addons:
  apt:
    packages:
      - libxml2-dev
r_packages:
  - devtools
r_github_packages:
  - datashield/DSI@resources
  - obiba/opalr@resources
warnings_are_errors: true